name: MiloTest

on:
  push:
    branches:
      - main
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Milo
        run : |
          curl -sf https://gobinaries.com/wawandco/milo/cmd/milo | sh
      - name: Iniciar milo
        run: |
          milo init
      - name: Realizar test
        run: |
          milo review .